language: node_js
node_js:
  - "10"
  - "12"
cache: npm
script:
  - lerna run test
before_script:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
  - cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
  - sudo apt-get install -y openjdk-9-jre gcc make ruby ruby-dev
  - yarn --version
  - lerna bootstrap
