language: node_js
node_js:
  - "7"
  - "8"
before_script:
  - "ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''"
  - "cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys"
  - "sudo apt-get install -y openjdk-7-jre gcc make ruby ruby-dev"
