
# docker-compose up --abort-on-container-exit

version: '2'
services:
  nodejs:
    build: .
    image: mecano_centos_nodejs
    volumes:
      - ../..:/mecano
    depends_on:
      - krb5
      - dind
    environment:
      MECANO_TEST: /mecano/docker/centos/test.coffee
      TEST_FILES: test # Filter with test/docker or test/docker/build.coffee
      # DEBUG: 1
      DOCKER_HOST: 'tcp://dind:2375' 
  dind:
    image: docker:dind
    privileged: true
    # detach: true
  krb5:
    image: sequenceiq/kerberos
    volumes:
      - /dev/urandom:/dev/random
    environment:
      BOOTSTRAP: 1
